[package]
name = "fetch-common"
version = "0.1.0"
edition = "2024"

[features]
cuda = ["ort/cuda"]
qnn = ["ort/qnn"]

[dependencies]
ort = { version = "2.0.0-rc.10", default-features = false, features = ["std"] }