name: Windows GUI Basic (ARM64)

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/windows-basic-template.yml
    with:
      architecture: arm64
      runner: windows-11-arm