name: Windows GUI Full (x64)

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/windows-full-template.yml
    with:
      architecture: x64
      runner: windows-latest
